### ISSUE TITLE
Bluetooth connection between Android and MacOS -> No Midi device visible on Mac

### ISSUE THREAD

**Issue by anzbert** [InvisibleWrench/FlutterMidiCommand#54]
Has anyone had luck using Bluetooth Midi with this package between an Android phone and Macos?

Steps I have been following:
1. Bluetooth pair phone to macbook
2. open Audio Midi Setup on mac and enter bluetooth settings
3. advertise bluetooth midi device
4. open Flutter Midi Command example app on phone and search for bluetooth devices -> macbook is visible
5. connect to macbook, which "appears" to be successful
6. check midi monitor app and/or ableton for any midi devices -> None visible!

if i run the example app in debug mode it will only show reoccuring ```onScanResult``` messages.

Any tips? Could there be a connection bug that I could try and find in the example app or Kotlin code?

edit: I dont have an iOS device to test it there. This comment is only regarding my Android experience.

**Comment by jrmilholland** [comment]
Running into a similar issue with iOS and bluetooth where the device will initially show, but then disappear out of the available devices listed. The really odd part is the device is still connected and will continue to function, but there's no devices listed.

**Comment by PasqualeTotaro** [comment]
Hi everyone. Have you since solved this?

I am on macOs, I can connect to my bluetooth MIDI device, the device seems connected (by looking at the device's status LED), but I do not see any MIDI input associated to it in my DAW.

Any suggestions?

**Comment by anzbert** [comment]
In the android midi documentation , Google links to this BLE Midi test app :

https://play.google.com/store/apps/details?id=com.mobileer.example.midibtlepairing

I haven't had any luck connecting to MacOS with it either. So maybe there
is a problem beyond what we can solve in this packages code.

**Comment by PasqualeTotaro** [comment]
From my end it looks like the device connects but it is not internally set-up as a MIDI device, it is just seen as a BLE device.

I think some extra steps are missing.

@anzbert can you help us on this?

**Comment by PasqualeTotaro** [comment]
I can connect my device via the default bluetooth MIDI menu on mac and it works. I trying to find a way to make it all automatic.

**Comment by anzbert** [comment]
By it works, do you mean it actually shows up in the DAW?

**Comment by PasqualeTotaro** [comment]
Yes :)

**Comment by mortenboye** [comment]
Hi @PasqualeTotaro I just replied to your email, but in the meantime I can offer a few details on things mentioned in this issue.
First, the issue that @jrmilholland mentions was isolated to the iOS implementation of this package and should be fixed in 0.4.8.
Second, the android implementation is simply a dart/flutter wrapper around [android-media-midi](https://developer.android.com/reference/android/media/midi/package-summary) which handles all BLE specifics, aside from scanning, behind the scenes. This is different from the iOS implementation, where there is no API to handle BLE MIDI, there is only the BLE (CoreBluetooth) APIs so the MIDI specifics are implemented on top of that by this package.
The android implementation, combined with the way BLE Midi is controlled on MacOS, which as @anzbert mentioned is through the Audio Midi Setup, makes is hard to dive deeper into the code to troubleshoot.

If possible, please provide more details about your setup, what is connecting to what and how, and what applications are running where, etc. etc.

**Comment by anzbert** [comment]
Oh wow that's great ! I am not sure if it gets better than that haha
